alpha: 1.0
batch_size: 256
buffer_size: 10000000
checkpoints_path: null
device: cuda
discount: 0.99
env: hammer-human-v1
eval_freq: 1000
expl_noise: 0.1
group: td3-bc-hammer-human-v1-multiseed-v0
load_model: ''
max_timesteps: 300000
n_episodes: 10
name: TD3-BC
noise_clip: 0.5
normalize: true
normalize_reward: false
policy_freq: 2
policy_noise: 0.2
project: offline-RL-init
seed: 0
tau: 0.005
