batch_size: 256
buffer_size: 10000000
checkpoints_path: null
device: cuda
discount: 0.99
env: hammer-cloned-v1
eval_freq: 1000
frac: 1.0
group: bc-hammer-cloned-v1-multiseed-v0
load_model: ''
max_timesteps: 300000
max_traj_len: 1000
n_episodes: 10
name: BC
normalize: true
project: offline-RL-init
seed: 0
